feat: assignment eight memory management
Sruthi-Subaraja/Csharp pull request #11
Opened 2023-09-08 07:03 UTC by Sruthi-Subaraja

ASSIGNMENT 8 - MEMORY MANAGEMENT
TASK 1 - Understanding and using value types and reference types in C#.
TASK 2 - Working with the stack and the heap.
TASK 3 - Using garbage collection and understanding it's impact on performance.
TASK 4 - Implementing and understanding the IDisposable interface and the 'using' statement

2023-09-20 13:09 UTC, Tharun-Sundar requested changes

2023-09-21 04:46 UTC, Sruthi-Subaraja commented on src/IDisposableDemo/FileClass.cs
> +namespace IDisposableDemo
There is a separate assignment for IDisposable design pattern, For this assignment, implementation of dispose method only is required for this assignment.

2023-09-22 03:35 UTC, Sruthi-Subaraja commented on src/IDisposableDemo/FileClass.cs
> +    public class FileClass : IDisposable
Done

2023-09-22 03:36 UTC, Sruthi-Subaraja commented on src/IDisposableDemo/FileClass.cs
> +        /// <value>Gstream writer object</value>
It's a typo. I've changed it.

2023-09-22 03:36 UTC, Sruthi-Subaraja commented on src/IDisposableDemo/FileClass.cs
> +        public StreamWriter? Sw { get; set; }
Done.

2023-09-22 04:31 UTC, Sruthi-Subaraja commented on src/IDisposableDemo/Program.cs
> +            StreamReader sr = new StreamReader("D:\\Csharp\\src\\IDisposableDemo\\textFile.txt");
If I use relative path, then the path won't be constant.

2023-09-22 04:33 UTC, Sruthi-Subaraja commented on src/IDisposableDemo/Program.cs
> +            using (StreamWriter sw = new StreamWriter("D:\\Csharp\\src\\IDisposableDemo\\textFile.txt"))
Okay

2023-09-22 04:52 UTC, Sruthi-Subaraja commented on src/IDisposableDemo/Program.cs
> +            using (StreamWriter sw = new StreamWriter("D:\\Csharp\\src\\IDisposableDemo\\textFile.txt"))
Yes, even when writing to a file in a separate method, Using is needed to close the file.

2023-09-22 13:25 UTC, Tharun-Sundar approved these changes

2023-09-22 13:25 UTC, Tharun-Sundar commented on src/IDisposableDemo/FileHandler.cs
> +        public StreamWriter FileWriter { get; set; }
Remove this property

2023-09-22 13:25 UTC, Tharun-Sundar commented on src/IDisposableDemo/FileClass.cs
> +﻿// <copyright file="FileClass.cs" company="PlaceholderCompany">
Remove this class

2023-09-22 14:02 UTC, Sruthi-Subaraja commented on src/IDisposableDemo/FileClass.cs
> +﻿// <copyright file="FileClass.cs" company="PlaceholderCompany">
Okay

2023-09-22 14:11 UTC, Sruthi-Subaraja commented on src/IDisposableDemo/FileHandler.cs
> +        public StreamWriter FileWriter { get; set; }
Okay

2023-09-23 04:03 UTC, merged