Assignment twelve collections and generics
Sruthi-Subaraja/Csharp pull request #14
Opened 2023-09-25 15:24 UTC by Sruthi-Subaraja

ASSIGNMENT 12 - COLLECTIONS AND GENERICS
To learn how to use different types of collections, perform operations on them, and apply generics to improve code reusability and maintainability.

2023-10-09 10:11 UTC, Tharun-Sundar requested changes

2023-10-09 10:11 UTC, Tharun-Sundar commented on src/CollectionsAndGenerics/Program.cs
> +                        int one = GetInput<int>("Enter integer one", integerRegex);
If the user gives 3 wrong inputs, by default -1 is the value considered. But the error message to the user says please try again. What is the proper error handling here?

2023-10-09 10:11 UTC, Tharun-Sundar commented on src/CollectionsAndGenerics/Program.cs
> +        private static string integerRegex = "^[0-9]$";
Why only integer regex is in a variable and not the other regex strings used?

2023-10-09 10:11 UTC, Tharun-Sundar commented on src/CollectionsAndGenerics/ListOperations.cs
> +                if (bookTitle == null)
This check should be outside the loop

2023-10-09 10:11 UTC, Tharun-Sundar commented on src/CollectionsAndGenerics/ListOperations.cs
> +                if (!bookTitle.Equals(this.List[i]))
Why not use `List.Contains()` here?

2023-10-18 10:19 UTC, Sruthi-Subaraja commented on src/CollectionsAndGenerics/ListOperations.cs
> +                if (!bookTitle.Equals(this.List[i]))
I changed it now

2023-10-18 10:20 UTC, Sruthi-Subaraja commented on src/CollectionsAndGenerics/Program.cs
> +        private static string integerRegex = "^[0-9]$";
That is used to get inputs for an IEnumerable to perform addition. Now i moved it inside the method instead of keeping it static.

2023-10-18 10:24 UTC, Sruthi-Subaraja commented on src/CollectionsAndGenerics/Program.cs
> +            int wrongInputCount = 1;
Updated it.

2023-10-18 10:36 UTC, Sruthi-Subaraja commented on src/CollectionsAndGenerics/Program.cs
> +                        DictionaryOperations<string, int> dictionaryOperations1 = new DictionaryOperations<string, int>("^[a-zA-Z ]*$", "^\\d+$");
Renamed it to dictionaryOperations.

2023-10-18 11:16 UTC, Sruthi-Subaraja commented on src/CollectionsAndGenerics/Program.cs
> +                        int one = GetInput<int>("Enter integer one", integerRegex);
I changed it now in such a way that the GetInput() method throws an exception, and it is handled in the upper layer.

2023-10-19 11:46 UTC, Tharun-Sundar approved these changes

2023-10-19 12:34 UTC, merged