Assignment eleven automated testing
Sruthi-Subaraja/Csharp pull request #15
Opened 2023-09-26 04:42 UTC by Sruthi-Subaraja

In progress PR:

ASSIGNMENT 11 - AUTOMATED TESTING
Task 1 - Setting up a test project using Xunit.
Task 2 - Writing the Application to Be Tested.

2023-09-26 09:35 UTC, Tharun-Sundar requested changes

2023-09-26 09:35 UTC, Tharun-Sundar commented on src/CalculationService/Calculator.cs
> +    /// To peerform basic calculation.
```suggestion
    /// To perform basic calculation.
```

2023-09-26 09:35 UTC, Tharun-Sundar commented on src/CalculationService/Calculator.cs
> +        /// <returns>Sum of Integer x and Integer y</returns>
What is integer x and integer y?

2023-10-03 14:14 UTC, Sruthi-Subaraja commented on src/CalculationService/Calculator.cs
> +    /// To peerform basic calculation.
Done

2023-10-03 14:15 UTC, Sruthi-Subaraja commented on src/CalculationService/Calculator.cs
> +        /// <returns>Sum of Integer x and Integer y</returns>
Two integer inputs. Changed it to a more meaningful name.

2023-10-09 09:30 UTC, Tharun-Sundar requested changes

2023-10-09 09:30 UTC, Tharun-Sundar commented on src/CalculationService/OrderService.cs
> +namespace CalculationService
Namespace doesn't match the class

2023-10-09 09:30 UTC, Tharun-Sundar commented on src/CalculationService/OrderService.cs
> +        /// <param name="orderId">Order Id.</param>
```suggestion
        /// <param name="orderId">Unique ID of the order</param>
```

2023-10-09 09:30 UTC, Tharun-Sundar commented on src/CalculationService/OrderService.cs
> +            Console.WriteLine("Order placed successfully");
This method is supposed to add products to the _orders dictionary. Why does it print a console message? This should be done by the caller.

2023-10-09 09:30 UTC, Tharun-Sundar commented on src/CalculationService/OrderService.cs
> +        /// <param name="orderId">Id of the order to edit.</param>
nit: Be consistent. As you have named the method `UpdateOrder`, the description of `orderId` can be "ID of the order to update. Similarly, the description of `productId` can be "ID of the product in the order to update." Also, in the description, it should be "ID" and not "Id".

2023-10-09 09:30 UTC, Tharun-Sundar commented on src/CalculationService/OrderService.cs
> +            this._orders.Remove(orderId);
What is this throws an error?

2023-10-09 09:30 UTC, Tharun-Sundar commented on src/CalculationService/OrderService.cs
> +        /// <param name="updatedCount">The count to be added to the order.</param>
If this is the count to be added, then why is it named `updatedCount`? It should be `countToBeAdded` or something similar.
Why send the count to be added instead of the updated count value itself? Seems to be unnecessary complication.

2023-10-09 09:30 UTC, Tharun-Sundar commented on src/CalculationService/OrderService.cs
> +            foreach (var item in this._orders[orderId])
What will happen if `_orders` doesn't have the orderId key?

2023-10-09 09:30 UTC, Tharun-Sundar commented on src/CalculationService/OrderService.cs
> +                item.ProductPrice += ProductInInventory.ProductsAvailable[orderId - 1].ProductPrice * updatedCount;
Why use "orderId - 1" for indexing here? What happens if an order is deleted?
Why is product price is a separate class that is not accessible in the product ordered?

2023-10-09 09:41 UTC, Tharun-Sundar requested changes

2023-10-09 09:41 UTC, Tharun-Sundar commented on src/CalculationService/ProductInInventory.cs
> +        public static List<ProductInInventory> ProductsAvailable { get; set; } = new List<ProductInInventory>();
Why this static variable? Please refactor the code to not use this static variable

2023-10-21 05:13 UTC, Sruthi-Subaraja commented on src/CalculationService/OrderService.cs
> +        /// <param name="orderId">Order Id.</param>
Updated.

2023-10-21 05:13 UTC, Sruthi-Subaraja commented on src/CalculationService/OrderService.cs
> +            Console.WriteLine("Order placed successfully");
Okay

2023-10-21 05:14 UTC, Sruthi-Subaraja commented on src/CalculationService/ProductInInventory.cs
> +        public static List<ProductInInventory> ProductsAvailable { get; set; } = new List<ProductInInventory>();
Updated it now.

2023-10-21 05:14 UTC, Sruthi-Subaraja commented on src/CalculationService/OrderService.cs
> +namespace CalculationService
It is given in the question in that way.

2023-10-21 05:17 UTC, Sruthi-Subaraja commented on src/CalculationService/OrderService.cs
> +        public virtual void AddOrder(int orderId, List<ProductOrdered> ordered)
Okay

2023-10-21 05:18 UTC, Sruthi-Subaraja commented on src/CalculationService/OrderService.cs
> +        /// <param name="updatedCount">The count to be added to the order.</param>
Okay

2023-10-21 05:19 UTC, Sruthi-Subaraja commented on src/CalculationService/OrderService.cs
> +            foreach (var item in this._orders[orderId])
It is validated before this method is called, anyways the application is updated now.

2023-10-21 05:21 UTC, Sruthi-Subaraja commented on src/CalculationService/OrderService.cs
> +        /// <param name="orderId">Id of the order to edit.</param>
Okay

2023-10-21 05:21 UTC, Sruthi-Subaraja commented on src/CalculationService/OrderService.cs
> +                item.ProductPrice += ProductInInventory.ProductsAvailable[orderId - 1].ProductPrice * updatedCount;
It is updated now.

2023-10-21 06:20 UTC, Sruthi-Subaraja commented on src/CalculationService/OrderService.cs
> +            this._orders.Remove(orderId);
.Remove() method doesn't throw exception, this only returns false if key is not found.

2023-10-30 11:34 UTC, Tharun-Sundar approved these changes

2023-10-30 11:34 UTC, Tharun-Sundar commented on src/CalculationService/Program.cs
> +            orderService.DeleteOrder(orderId);
Why is this needed? This is repeated in line 92.

2023-11-07 08:36 UTC, Sruthi-Subaraja commented on src/CalculationService/Program.cs
> +            orderService.DeleteOrder(orderId);
This is not needed, this was a mistake.

2023-11-07 08:47 UTC, merged