assignment thirteen advanced language features
Sruthi-Subaraja/Csharp pull request #16
Opened 2023-09-26 15:28 UTC by Sruthi-Subaraja

ASSIGNMENT 13 - ADVANCED LANGUAGE FEATURES
TASK 1 - Understanding and Implementing Events and Delegates in C#.
TASK 2 - Understanding the Use of Dynamic and Var Keywords and Their Differences.
TASK 3 - Implementing Anonymous Methods.

2023-09-27 11:41 UTC, Tharun-Sundar requested changes

2023-09-27 11:41 UTC, Tharun-Sundar commented on src/AdvancedLanguageFeatures/Program.cs
> +            return (T)Convert.ChangeType(-1, typeof(T));
What happens when you return (T)(-1) instead?

2023-09-27 11:41 UTC, Tharun-Sundar commented on src/AdvancedLanguageFeatures/Program.cs
> +                else
As you are returning with the `if`, the else is not needed.

2023-09-27 11:41 UTC, Tharun-Sundar commented on src/AdvancedLanguageFeatures/Program.cs
> +        /// Task three using anonymous function for comparison.
```suggestion
        /// Task three: Using anonymous function for comparison.
```

2023-09-27 11:41 UTC, Tharun-Sundar commented on src/AdvancedLanguageFeatures/Program.cs
> +        /// Task two difference between var and dynamic
```suggestion
        /// Task two: Difference between var and dynamic
```

2023-09-27 11:41 UTC, Tharun-Sundar commented on src/AdvancedLanguageFeatures/Program.cs
> +            string messageToPrint = ValidateInput<string>("Enter any message to Print", "(.*?)");
```suggestion
            string messageToPrint = ValidateInput<string>("Enter any message to print", "(.*?)");
```

2023-09-27 11:41 UTC, Tharun-Sundar commented on src/AdvancedLanguageFeatures/Program.cs
> +        /// Task one invoking an event
```suggestion
        /// Task one: Invoking an event
```

2023-09-27 12:20 UTC, Tharun-Sundar requested changes

2023-09-28 10:37 UTC, Sruthi-Subaraja commented on README.md
> +TASK 1 - Understanding and Implementing Events and Delegates in C#.
Changed.

2023-09-28 10:37 UTC, Sruthi-Subaraja commented on README.md
> +TASK 3 - Implementing Anonymous Methods.
Done

2023-09-28 10:37 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +                else
Okay

2023-09-28 10:38 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +        /// Task two difference between var and dynamic
Okay

2023-09-28 10:38 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +        /// Task one invoking an event
Okay

2023-09-28 10:38 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +        /// Task three using anonymous function for comparison.
Okay

2023-09-28 10:38 UTC, Sruthi-Subaraja commented on README.md
> +TASK 2 - Understanding the Use of Dynamic and Var Keywords and Their Differences.
Done

2023-09-28 10:38 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +            string messageToPrint = ValidateInput<string>("Enter any message to Print", "(.*?)");
Done

2023-09-28 10:39 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +            for (int i = 0; i < 3; i++)
Okay Tharun

2023-09-28 10:39 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +        /// <param name="regexToCompareWith">Regex to compare with</param>
Done

2023-09-28 10:40 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +        public static bool IsInputValid(string input,  string regexToCompareWith)
Done

2023-09-28 10:41 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +            return input;
Okay

2023-09-28 10:42 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +        /// Checks if the input is valid.
Done

2023-09-28 10:42 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +            string? input = Console.ReadLine();
Okay

2023-09-28 10:43 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +        /// <param name="messageToPrint">The message printed for the user</param>
Okay

2023-09-28 10:44 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +        /// <typeparam name="T">String or integer</typeparam>
Done

2023-09-28 10:47 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +            return (T)Convert.ChangeType(-1, typeof(T));
We can't convert int type to T type

2023-10-03 09:12 UTC, Tharun-Sundar requested changes

2023-10-03 09:12 UTC, Tharun-Sundar commented on tests/unit/AdvancedLanguageFeatures/TaskManagerClassTests/TaskManagerClassTests.cs
> +    {
Test names need to be updated

2023-10-04 12:51 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Notifier.cs
> +        /// Notifies the user with message
Changed it to a more appropriate summary.

2023-10-04 12:51 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Notifier.cs
> +        /// Event of Notify delegate type
Changed it.

2023-10-04 13:01 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/TaskManager.cs
> +                case null:
It is not needed.

2023-10-04 13:06 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/TaskManager.cs
> +            var (title, author, isbn) = book;
Yes, it is the requirement to use deconstruction to print the book details.

2023-10-04 13:18 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Shape.cs
> +        public string? Color { get; set; }
Okay

2023-10-04 13:18 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/TaskManager.cs
> +            number = number.Where(x => x % 2 != 0).ToList();
Okay done

2023-10-04 13:21 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +        {
Okay

2023-10-04 13:21 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Program.cs
> +                Console.Write(array[i] + ",");
Okay

2023-10-05 04:31 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Notifier.cs
> +        public virtual void OnOnAction(string message)
It is not needed

2023-10-05 04:39 UTC, Sruthi-Subaraja commented on src/AdvancedLanguageFeatures/Circle.cs
> +    /// Circle class with properties radius and calculates area with it.
Okay

2023-10-05 04:42 UTC, Sruthi-Subaraja commented on tests/unit/AdvancedLanguageFeatures/NotifierClassTests/NotifierClassTest.cs
> +        public void NoEvent_InvokeOnActionEvent_ExecuteTheMethodsSubscribed()
Done

2023-10-05 08:54 UTC, Sruthi-Subaraja commented on tests/unit/AdvancedLanguageFeatures/TaskManagerClassTests/TaskManagerClassTests.cs
> +    {
Done

2023-10-09 07:36 UTC, Tharun-Sundar approved these changes

2023-10-09 07:36 UTC, Tharun-Sundar commented on tests/unit/AdvancedLanguageFeatures/TaskManagerClassTests/TaskManagerClassTests.cs
> +        public void ListWithPositiveAndNegativeNumbers_RunTaskFour_ReturnSquareOfTheOddNumbersOnly()
The test given part says there will be a list with positive and negative numbers. But the input `listofNumber` only has positive numbers.

2023-10-18 08:40 UTC, Sruthi-Subaraja commented on tests/unit/AdvancedLanguageFeatures/TaskManagerClassTests/TaskManagerClassTests.cs
> +        public void TwoProducts_ProductNamesAreCompared_ReturnPositiveInteger()
Okay

2023-10-18 08:44 UTC, Sruthi-Subaraja commented on tests/unit/AdvancedLanguageFeatures/TaskManagerClassTests/TaskManagerClassTests.cs
> +        public void ListWithPositiveAndNegativeNumbers_RunTaskFour_ReturnSquareOfTheOddNumbersOnly()
The list will contain odd and even numbers. I made a mistake naming it positive and negative integers.

2023-10-19 13:13 UTC, merged