Assignment fourteen asynchronous programming
Sruthi-Subaraja/Csharp pull request #17
Opened 2023-10-04 12:31 UTC by Sruthi-Subaraja

ASSIGNMENT 14 -ASYNCHRONOUS PROGRAMMING
To gain in-depth understanding and practical experience of Async/Await, Task Parallel Library (TPL), and Multi-Threading in C#.
TASK 1 - Understanding and implementing async/await.
TASK 2 - Implementing and understanding Task Parallel Library.
TASK 3 - Advanced understanding and usage of multi-threading.
TASK 4 - Implementing multi-layered async/await operations in a real-world scenario.
TASK 5 - Debugging and fixing deadlock conditions.
TASK 6 - Real-world application of ConfigureAwait in a console application with thread tracking.
TASK 7 - Understanding the difference between async void and async task with exceptions.

2023-10-13 07:36 UTC, Tharun-Sundar requested changes

2023-10-13 07:36 UTC, Tharun-Sundar commented on src/AsynchronousProgramming/Deadlock.cs
> +            // var result = SomeAsyncOperation().Result; // will make the main thread wait causing a deadlock
Explain why blocking the main thread causes deadlock. Doesn't using await make the thread wait until the awaited operation is done?

2023-10-13 07:36 UTC, Tharun-Sundar commented on src/AsynchronousProgramming/ApplicationWithConfigureAwait.cs
> +            TaskParallelLibraryImplementation.PrintArrayUsingParallerThreads(result);
Why is this method called here?

2023-10-13 07:36 UTC, Tharun-Sundar commented on tests/unit/AsynchronousProgramming/AsyncAndAwaitClassTest/AsyncAndAwaitClassTest.cs
> +            string url = "https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread?view=net-7.0";
This test has the same logic used in the method which is wring. Tests should not have logic like this. It should only call methods written in the main code.

2023-10-13 07:36 UTC, Tharun-Sundar commented on tests/unit/AsynchronousProgramming/AsyncAndAwaitClassTest/AsyncAndAwaitClassTest.cs
> +        public async void URL_GettingContentsFromURL_ReturnTheContentsOfURL()
```suggestion
        public async void Url_GettingContentsFromUrl_ReturnTheContentsOfUrl()
```

2023-10-18 11:44 UTC, Sruthi-Subaraja commented on src/AsynchronousProgramming/AsyncAndAwait.cs
> +        public static async Task<string> GetContentsOfURL(string url)
Done

2023-10-18 12:46 UTC, Sruthi-Subaraja commented on src/AsynchronousProgramming/AsyncAndAwait.cs
> +        public static async Task<string> GetContentsOfURL(string url)
Okay

2023-10-18 12:47 UTC, Sruthi-Subaraja commented on src/AsynchronousProgramming/Program.cs
> +                        for (int i = 0; i < 10000; i++)
Done

2023-10-18 12:48 UTC, Sruthi-Subaraja commented on src/AsynchronousProgramming/Program.cs
> +                    default:
Missed that. I updated it now.

2023-10-18 12:59 UTC, Sruthi-Subaraja commented on src/AsynchronousProgramming/TaskParallelLibraryImplementation.cs
> +        public static void PrintArrayUsingParallerThreads(int[] arrayOfIntegers)
Changed it.

2023-10-18 13:10 UTC, Sruthi-Subaraja commented on src/AsynchronousProgramming/ApplicationWithConfigureAwait.cs
> +            TaskParallelLibraryImplementation.PrintArrayUsingParallerThreads(result);
It is not necessary, I only added that to have a long running operation. I removed it and only have MethodA() as method that executes a long running operation.

2023-10-18 13:13 UTC, Sruthi-Subaraja commented on src/AsynchronousProgramming/Deadlock.cs
> +            // var result = SomeAsyncOperation().Result; // will make the main thread wait causing a deadlock
I'll explain it in the README.md.

2023-10-18 14:16 UTC, Sruthi-Subaraja commented on src/AsynchronousProgramming/MultiThreading.cs
> +        public static async Task UsingMultiThreadingToAddAndMultiply()
The methods will be executed by the caller thread if the methods are called without a new thread. The thread.Join() could be used after starting both the threads which would indicate that the methods are started the execution simultaneously but will wait until both the execution is called.

2023-10-18 14:26 UTC, Sruthi-Subaraja commented on tests/unit/AsynchronousProgramming/AsyncAndAwaitClassTest/AsyncAndAwaitClassTest.cs
> +        public async void URL_GettingContentsFromURL_ReturnTheContentsOfURL()
Done.

2023-10-21 06:33 UTC, Sruthi-Subaraja commented on tests/unit/AsynchronousProgramming/AsyncAndAwaitClassTest/AsyncAndAwaitClassTest.cs
> +            string url = "https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread?view=net-7.0";
The GetStringAsync() method is not overridable, how else can I mock and test the method?

2023-10-27 11:17 UTC, Tharun-Sundar commented on tests/unit/AsynchronousProgramming/AsyncAndAwaitClassTest/AsyncAndAwaitClassTest.cs
> +            string url = "https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread?view=net-7.0";
Then this test is not needed

2023-10-27 12:06 UTC, Sruthi-Subaraja commented on tests/unit/AsynchronousProgramming/AsyncAndAwaitClassTest/AsyncAndAwaitClassTest.cs
> +            string url = "https://learn.microsoft.com/en-us/dotnet/api/system.threading.thread?view=net-7.0";
Okay.

2023-10-30 10:09 UTC, Tharun-Sundar approved these changes

2023-11-07 09:02 UTC, merged