Assignment fifteen IDispose pattern
Sruthi-Subaraja/Csharp pull request #18
Opened 2023-10-05 15:00 UTC by Sruthi-Subaraja

ASSIGNMENT 15 - IDISPOSE PATTERN
TASK 1 - Understanding the difference between managed and unmanaged resource.
TASK 2 - Implementing the IDisposable interface.
TASK 3 - Implementing the dispose pattern.
TASK 4 - Using finalizers.

2023-10-13 12:07 UTC, Tharun-Sundar requested changes

2023-10-13 12:07 UTC, Tharun-Sundar commented on src/IDisposePattern/Program.cs
> +            string filePath = Path.Combine(currentDirectory, "test.txt");
Where is filePath used?

2023-10-13 12:07 UTC, Tharun-Sundar commented on tests/unit/IDisposePattern/UnmanagedResourceClassTest/UnmanagedResourceClassTest.cs
> +            StreamReader streamReader = new StreamReader("test.txt");
StreamReader should not be used here. It should be mocked

2023-10-19 15:11 UTC, Sruthi-Subaraja commented on tests/unit/IDisposePattern/ManagedResourcesClassTest/ManagedResourceClassTest.cs
> +            Assert.Equal(expectedValue, managedResource.Data.Count());
Okay

2023-10-19 15:11 UTC, Sruthi-Subaraja commented on src/IDisposePattern/Program.cs
> +            string filePath = Path.Combine(currentDirectory, "test.txt");
It is not needed, I removed it.

2023-10-19 15:17 UTC, Sruthi-Subaraja commented on src/IDisposePattern/ManagedResource.cs
> +        public List<string> Data { get; set; } = new List<string>();
I'll need it outside of the class to test it and print it's values, so I updated it to private set now.

2023-10-20 04:00 UTC, Sruthi-Subaraja commented on tests/unit/IDisposePattern/UnmanagedResourceClassTest/UnmanagedResourceClassTest.cs
> +            StreamReader streamReader = new StreamReader("test.txt");
Okay done

2023-10-30 11:36 UTC, Tharun-Sundar approved these changes

2023-10-30 11:36 UTC, Tharun-Sundar commented on tests/unit/IDisposePattern/ManagedResourcesClassTest/ManagedResourceClassTest.cs
> +            int expectedValue = 1;
Variable name can be `expectedCount`

2023-11-07 09:23 UTC, Sruthi-Subaraja commented on tests/unit/IDisposePattern/ManagedResourcesClassTest/ManagedResourceClassTest.cs
> +            int expectedValue = 1;
Okay, changes made.

2023-11-07 09:23 UTC, merged