Feat assignmentone task
Sruthi-Subaraja/Csharp pull request #2
Opened 2023-08-16 04:14 UTC by Sruthi-Subaraja

The exploration questions and the answers to the questions are given in the Exploration.MD. The questions were answered by using the research materials and googling concepts. 

The task is to implement a class "MathUtils" which will take two inputs from the user and using function Add, Subtract, Multiply, Divide, the program returns the sum, difference, product and quotient.

The Program.cs file contains the class Program which gets the input from the user and calls the functions Add(input1, input2), Sub(input1, input2), Mul(input1, input2), Div(input1, input2) and DisplayResults().

The MathUtils.cs file contains the class MathUtils. The class contains the methods Add(input1, input2) which returns the sum of input1 and input2, Sub(input1, input2) which returns the difference of input1 and input2, Mul(input1, input2) which returns the product of input1 and input2, Div(input1, input2y) which returns the quotient when input1 is divided by input2 and DisplayResults() displays the values returned from the previous funtions.

2023-08-17 08:44 UTC, Tharun-Sundar requested changes

2023-08-18 04:28 UTC, Sruthi-Subaraja commented on src/Assignment1/Program.cs
> +            int input1 = Convert.ToInt32(string1);
To handle that TryParse() is used so that the input can only be an integer.

2023-08-18 04:29 UTC, Sruthi-Subaraja commented on src/Assignment1/MathUtils.cs
> +    /// MathUtils class
Done

2023-08-21 08:29 UTC, Tharun-Sundar requested changes

2023-08-21 08:29 UTC, Tharun-Sundar commented on src/Assignment1/Program.cs
> +        private static int CheckIfInteger(string? stringToCheck)
This function is named CheckIfInteger. But it is also getting input from the user. A function should focus on a particular task.

2023-08-22 09:09 UTC, Tharun-Sundar commented
The project file is not linked to the solution. Was this intentional?

2023-08-22 10:06 UTC, Sruthi-Subaraja commented
It was a mistake. The project file is linked to the solution file now.

2023-08-22 11:36 UTC, Tharun-Sundar approved these changes

2023-08-23 04:26 UTC, merged