Assignment nineteen linq operations
Sruthi-Subaraja/Csharp pull request #22
Opened 2023-10-13 15:24 UTC by Sruthi-Subaraja

In progress

2023-10-15 08:31 UTC, Tharun-Sundar approved these changes

2023-10-15 08:31 UTC, Tharun-Sundar commented on src/Linq/TaskManager.cs
> +        public void RunTaskOne(List<Product> products, LinqOperations linqOperations)
Average of filtered prices in missing

2023-10-15 08:31 UTC, Tharun-Sundar commented on src/Linq/LinqOperations.cs
> +            return products.GroupBy(product => product.Category).Select(product => Tuple.Create(product.Key, product.Count(), product.OrderByDescending(x => x.Price).ElementAt(0).ProductName));
The variable used inside Select should be named as productGroup

2023-10-15 08:34 UTC, Tharun-Sundar requested changes
Add the pending task

2023-10-16 04:40 UTC, Sruthi-Subaraja commented on src/Linq/LinqOperations.cs
> +            return products.GroupBy(product => product.Category).Select(product => Tuple.Create(product.Key, product.Count(), product.OrderByDescending(x => x.Price).ElementAt(0).ProductName));
Okay

2023-10-17 04:06 UTC, Sruthi-Subaraja commented on src/Linq/TaskManager.cs
> +        public void RunTaskOne(List<Product> products, LinqOperations linqOperations)
I added it now.

2023-10-30 11:39 UTC, Tharun-Sundar approved these changes

2023-10-31 12:28 UTC, merged