feat: task one memory optimization
Sruthi-Subaraja/Csharp pull request #8
Opened 2023-09-04 09:09 UTC by Sruthi-Subaraja

To learn how to detect, diagnose, and resolve memory issues in c# codebase and also to discuss best practices for memory management and use tools for memory profiling.

2023-09-14 08:59 UTC, Tharun-Sundar requested changes

2023-09-14 08:59 UTC, Tharun-Sundar commented on README.md
> +To learn how to detect, diagnose, and resolve memory issues in c# codebase and also to discuss best practices for memory management and use tools for memory profiling.
Split this statement into two statements

2023-09-14 08:59 UTC, Tharun-Sundar commented on src/MemoryOptimization/MemoryEater.cs
> +    /// Class to check memory allocaation
This class is not checking for memory allocation. It exposes a method to allocate memory to a variable.

2023-09-14 08:59 UTC, Tharun-Sundar commented on src/MemoryOptimization/MemoryEater.cs
> +                /// <summary>
Why is this comment needed for a local variable?

2023-09-14 08:59 UTC, Tharun-Sundar commented on src/MemoryOptimization/README.md
> +In the debug menu, select diagnostic tools to open a diagnostic window. When the application is built and executed the process memory can be monitored also the GC collection in the diagnostic tools.
Rephrase the statement properly

2023-09-14 08:59 UTC, Tharun-Sundar commented on src/MemoryOptimization/README.md
> +In the code it is said that the list is used only inside the while(true) loop, so moving the declaration of the list inside the while(true) loop optimizes the memory because for every iteration a new
Rephrase this statement properly

2023-09-14 08:59 UTC, Tharun-Sundar commented on src/MemoryOptimization/README.md
> +Before optimizing the code the list is declared once and a new large array object is added to the list for every iteration, the process memory gradually increases with every iteration and throws a ou
Don't combine two statements into a single statement.

2023-09-14 08:59 UTC, Tharun-Sundar commented on src/MemoryOptimization/README.md
> +Memory optimization is essential to ensure that is application can handle large amounts of data and continue to work the way we intend it to work. The diagnostic tools help monitor the memory usage o
This paragraph seems to be related to the previous solution you had for this assignment.

2023-09-15 12:56 UTC, Sruthi-Subaraja commented on README.md
> +To learn how to detect, diagnose, and resolve memory issues in c# codebase and also to discuss best practices for memory management and use tools for memory profiling.
Done

2023-09-15 12:57 UTC, Sruthi-Subaraja commented on src/MemoryOptimization/MemoryEater.cs
> +    /// Class to check memory allocaation
Changed the summary

2023-09-15 12:58 UTC, Sruthi-Subaraja commented on src/MemoryOptimization/README.md
> +Before optimizing the code the list is declared once and a new large array object is added to the list for every iteration, the process memory gradually increases with every iteration and throws a ou
It is split into points.

2023-09-15 12:59 UTC, Sruthi-Subaraja commented on src/MemoryOptimization/README.md
> +Memory optimization is essential to ensure that is application can handle large amounts of data and continue to work the way we intend it to work. The diagnostic tools help monitor the memory usage o
Updated it to match the new solution.

2023-09-20 12:23 UTC, Tharun-Sundar approved these changes

2023-09-21 04:32 UTC, Sruthi-Subaraja commented on src/MemoryOptimization/MemoryEater.cs
> +                /// <summary>
It is not needed. So I removed it.

2023-09-21 04:33 UTC, merged